name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core 2.1 for Sonar
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.3

    - name: Setup .NET Core for Actual Source
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
 
    - name: Install sonar scanner .net Global Tool
      run: dotnet tool install --global dotnet-sonarscanner --version 4.7.1

    - name: Install src dependencies
      run: dotnet restore src/FakeXrmEasy.Core.csproj

    - name: SonarCloud Begin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      run: dotnet sonarscanner begin /k:"${SONAR_PROJECT_KEY}" /o:"dynamicsvalue" /d:sonar.login="${SONAR_TOKEN}"
      
    - name: Build src proj
      run: dotnet build src/FakeXrmEasy.Core.csproj --configuration Debug --no-restore

    - name: Install test dependencies
      run: dotnet restore tests/FakeXrmEasy.Core.Tests.csproj

    - name: Build test proj
      run: dotnet build tests/FakeXrmEasy.Core.Tests.csproj --configuration Debug --no-restore
  
    - name: Test
      run: dotnet test tests/FakeXrmEasy.Core.Tests.csproj --configuration Debug --no-restore --verbosity normal
    
    - name: SonarCloud End
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: dotnet sonarscanner end /d:sonar.login="<token>" 
    
    
    
